export const checklistAire = [
  "Verificación visual del estado físico del equipo",
  "Pruebas de funcionamiento previas al mantenimiento",
  "Corroboración de activación de alarmas",
  "Verificación de conexión a tierra física",
  "Limpieza general de gabinete",
  "Mantenimiento a condensador",
  "Retirar material residual",
  "Alineación de serpentín",
  "Lavado con químicos FOAM CLEANER",
  "Colocación de tableta PAN CLEAN",
  "Mantenimiento a compresor",
  "Mantenimiento a ventilador",
  "Mantenimiento a evaporador",
  "Verificación de válvula de expansión",
  "Verificación de carga de gas",
  "Sistema de arranque del compresor",
  "Sensor de temperatura",
  "Calibración de control de temperatura",
  "Consumo de amperaje",
  "Limpieza general",
  "Reemplazo de filtros",
  "Motores en extractores",
  "Motores en inyectores",
  "Bandas y aspiradores",
  "Puesta en marcha",
  "Pruebas de esfuerzo"
];
